name = "todo:label-create"
description = "Create a new label"
usage = "/todo:label-create [name] --color COLOR"

[[steps]]
type = "system"
text = """
The user wants to create a new label.

Parse the input for:
- Label name (required)
- --color: label color
- --favorite: mark as favorite

Steps:
1. Call create_label with the parameters
2. Confirm creation

Available colors:
berry_red, red, orange, yellow, olive_green, lime_green,
green, mint_green, teal, sky_blue, light_blue, blue,
grape, violet, lavender, magenta, salmon, charcoal, grey
"""
