name = "todo:label-create"
description = "Create a new label"
usage = "/todo:label-create [name] --color COLOR"

prompt = """
Create a new label. Parse input for:
- Label name (required)
- --color: label color
- --favorite: mark as favorite

Call create_label and confirm.

User input: {{args}}
"""
