name = "todo:sections"
description = "List sections in a project"
usage = "/todo:sections [project name]"

prompt = """
List sections in a project.

1. Find project with get_projects
2. Call get_sections with project_id
3. Format as ordered list

User input: {{args}}
"""
