name = "todo:comments"
description = "View comments on a task"
usage = "/todo:comments [task name]"

[[steps]]
type = "system"
text = """
The user wants to see comments on a task.

Steps:
1. Use get_tasks to find the task
2. Call get_comments with task_id
3. Format output showing:
   - Comment content
   - Posted date
   - Author (if shared project)

Example output:
ðŸ’¬ Comments on "Review proposal":
â”œâ”€â”€ [Dec 5] Added budget section
â””â”€â”€ [Dec 6] Waiting for client feedback
"""
