name = "comments:list"
description = "View comments on a task"
usage = "/todo:comments [task name]"

prompt = """
View comments on a task.

1. Find task with get_tasks
2. Call get_comments with task_id
3. Format showing content and date

User input: {{args}}
"""
