name = "projects:create"
description = "Create a new Todoist project"
usage = "/todo:project-create [name] --color COLOR --view list|board"

prompt = """
Create a new project. Parse input for:
- Project name (required)
- --color: project color
- --view: list or board
- --favorite: mark as favorite
- --parent: parent project name

Call create_project and confirm creation.

Colors: berry_red, red, orange, yellow, green, blue, grape, violet, grey

User input: {{args}}
"""
